apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psap-control-center-data
  labels:
    app: psap-control-center
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psap-control-center-kubeconfigs
  labels:
    app: psap-control-center
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
